/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityAction = { 'walletDebited' : null } |
  { 'walletCredited' : null } |
  { 'withdrawalApproved' : null } |
  { 'taskApproved' : null } |
  { 'proofUploaded' : null } |
  { 'taskRejected' : null } |
  { 'withdrawalRequested' : null } |
  { 'taskCreated' : null } |
  { 'taskAccepted' : null };
export interface ActivityLogEntry {
  'action' : ActivityAction,
  'user' : Principal,
  'timestamp' : Time,
  'relatedTask' : [] | [string],
}
export interface AdPlacement {
  'id' : string,
  'content' : string,
  'adType' : AdType,
  'frequency' : bigint,
}
export type AdType = { 'taskBanner' : null } |
  { 'taskCompletionInterstitial' : null } |
  { 'dashboardBanner' : null };
export type ExternalBlob = Uint8Array;
export interface Task {
  'id' : string,
  'status' : TaskStatus,
  'title' : string,
  'provider' : Principal,
  'timeRequired' : string,
  'acceptanceDeadline' : [] | [Time],
  'revisionCount' : bigint,
  'description' : string,
  'category' : string,
  'proof' : TaskProof,
  'acceptedBy' : [] | [Principal],
  'paymentAmount' : bigint,
  'location' : string,
}
export interface TaskProof {
  'proofFiles' : Array<ExternalBlob>,
  'submittedAt' : Time,
}
export type TaskStatus = { 'proofSubmitted' : null } |
  { 'assigned' : null } |
  { 'underReview' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'pendingApproval' : null } |
  { 'rejected' : null } |
  { 'declined' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface TransactionRecord {
  'id' : string,
  'transactionDate' : Time,
  'transactionType' : TransactionType,
  'user' : Principal,
  'amount' : bigint,
}
export interface TransactionRecordExtended {
  'id' : string,
  'transactionDate' : Time,
  'transactionType' : TransactionType,
  'user' : Principal,
  'relatedTaskId' : [] | [string],
  'relatedTaskTitle' : [] | [string],
  'amount' : bigint,
}
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null } |
  { 'taskPayment' : null } |
  { 'payout' : null };
export interface User {
  'pendingVerification' : boolean,
  'verified' : boolean,
  'appRole' : UserAppRole,
  'name' : string,
  'year' : bigint,
  'verificationDocument' : [] | [ExternalBlob],
  'phoneNumber' : string,
  'profilePicture' : [] | [ExternalBlob],
  'college' : string,
}
export type UserAppRole = { 'taskPoster' : null } |
  { 'business' : null } |
  { 'student' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerificationRequest {
  'user' : Principal,
  'verificationDocument' : ExternalBlob,
}
export interface WithdrawalRequest {
  'id' : string,
  'status' : WithdrawalStatus,
  'createdAt' : Time,
  'user' : Principal,
  'amount' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTask' : ActorMethod<[string], undefined>,
  'applyForTask' : ActorMethod<[string, string], undefined>,
  'approveTask' : ActorMethod<[string], undefined>,
  'approveWithdrawRequest' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[Task], undefined>,
  'createWithdrawRequest' : ActorMethod<[string, bigint], undefined>,
  'depositToWallet' : ActorMethod<[bigint], undefined>,
  'ensureDemoDataSeeded' : ActorMethod<[], undefined>,
  'getActivityLog' : ActorMethod<[], Array<ActivityLogEntry>>,
  'getAdPlacement' : ActorMethod<[AdType], AdPlacement>,
  'getAdPlacements' : ActorMethod<[], Array<AdPlacement>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTransactionHistory' : ActorMethod<[], Array<TransactionRecord>>,
  'getAllTransactionHistoryExtended' : ActorMethod<
    [],
    Array<TransactionRecordExtended>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepositBalance' : ActorMethod<[], bigint>,
  'getOpenTasks' : ActorMethod<[], Array<Task>>,
  'getPendingVerificationRequests' : ActorMethod<
    [],
    Array<VerificationRequest>
  >,
  'getPendingWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getProofFiles' : ActorMethod<[string], Array<ExternalBlob>>,
  'getTask' : ActorMethod<[string], [] | [Task]>,
  'getTasksByUser' : ActorMethod<[Principal], Array<Task>>,
  'getTransactionHistory' : ActorMethod<[], Array<TransactionRecord>>,
  'getUserAppRole' : ActorMethod<[], [] | [UserAppRole]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDemoDataSeeded' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[UserRole, UserAppRole, string, string], UserRole>,
  'rejectWithdrawRequest' : ActorMethod<[string], undefined>,
  'requestTaskRevision' : ActorMethod<[string], undefined>,
  'resetAdPlacements' : ActorMethod<[], undefined>,
  'reviewTask' : ActorMethod<[string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[User], undefined>,
  'setDemoDataSeeded' : ActorMethod<[], undefined>,
  'submitCollegeVerification' : ActorMethod<
    [string, bigint, ExternalBlob],
    undefined
  >,
  'submitTaskProof' : ActorMethod<[string, Array<ExternalBlob>], undefined>,
  'updateAdPlacement' : ActorMethod<[AdType, AdPlacement], undefined>,
  'updateProfile' : ActorMethod<[string, bigint], undefined>,
  'uploadProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
  'verifyUser' : ActorMethod<[Principal, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];