/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'proofSubmitted' : IDL.Null,
  'assigned' : IDL.Null,
  'underReview' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'pendingApproval' : IDL.Null,
  'rejected' : IDL.Null,
  'declined' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TaskProof = IDL.Record({
  'proofFiles' : IDL.Vec(ExternalBlob),
  'submittedAt' : Time,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'provider' : IDL.Principal,
  'timeRequired' : IDL.Text,
  'acceptanceDeadline' : IDL.Opt(Time),
  'revisionCount' : IDL.Nat,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'proof' : TaskProof,
  'acceptedBy' : IDL.Opt(IDL.Principal),
  'paymentAmount' : IDL.Nat,
  'location' : IDL.Text,
});
export const ActivityAction = IDL.Variant({
  'walletDebited' : IDL.Null,
  'walletCredited' : IDL.Null,
  'withdrawalApproved' : IDL.Null,
  'taskApproved' : IDL.Null,
  'proofUploaded' : IDL.Null,
  'taskRejected' : IDL.Null,
  'withdrawalRequested' : IDL.Null,
  'taskCreated' : IDL.Null,
  'taskAccepted' : IDL.Null,
});
export const ActivityLogEntry = IDL.Record({
  'action' : ActivityAction,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'relatedTask' : IDL.Opt(IDL.Text),
});
export const AdType = IDL.Variant({
  'taskBanner' : IDL.Null,
  'taskCompletionInterstitial' : IDL.Null,
  'dashboardBanner' : IDL.Null,
});
export const AdPlacement = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'adType' : AdType,
  'frequency' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'taskPayment' : IDL.Null,
  'payout' : IDL.Null,
});
export const TransactionRecord = IDL.Record({
  'id' : IDL.Text,
  'transactionDate' : Time,
  'transactionType' : TransactionType,
  'user' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const TransactionRecordExtended = IDL.Record({
  'id' : IDL.Text,
  'transactionDate' : Time,
  'transactionType' : TransactionType,
  'user' : IDL.Principal,
  'relatedTaskId' : IDL.Opt(IDL.Text),
  'relatedTaskTitle' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UserAppRole = IDL.Variant({
  'taskPoster' : IDL.Null,
  'business' : IDL.Null,
  'student' : IDL.Null,
});
export const User = IDL.Record({
  'pendingVerification' : IDL.Bool,
  'verified' : IDL.Bool,
  'appRole' : UserAppRole,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'verificationDocument' : IDL.Opt(ExternalBlob),
  'phoneNumber' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'college' : IDL.Text,
});
export const VerificationRequest = IDL.Record({
  'user' : IDL.Principal,
  'verificationDocument' : ExternalBlob,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : WithdrawalStatus,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTask' : IDL.Func([IDL.Text], [], []),
  'applyForTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'approveTask' : IDL.Func([IDL.Text], [], []),
  'approveWithdrawRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([Task], [], []),
  'createWithdrawRequest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'depositToWallet' : IDL.Func([IDL.Nat], [], []),
  'ensureDemoDataSeeded' : IDL.Func([], [], []),
  'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLogEntry)], ['query']),
  'getAdPlacement' : IDL.Func([AdType], [AdPlacement], ['query']),
  'getAdPlacements' : IDL.Func([], [IDL.Vec(AdPlacement)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getAllTransactionHistoryExtended' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecordExtended)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepositBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getOpenTasks' : IDL.Func([], [IDL.Vec(Task)], []),
  'getPendingVerificationRequests' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequest)],
      ['query'],
    ),
  'getPendingWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getProofFiles' : IDL.Func([IDL.Text], [IDL.Vec(ExternalBlob)], ['query']),
  'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'getTasksByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getUserAppRole' : IDL.Func([], [IDL.Opt(UserAppRole)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDemoDataSeeded' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func(
      [UserRole, UserAppRole, IDL.Text, IDL.Text],
      [UserRole],
      [],
    ),
  'rejectWithdrawRequest' : IDL.Func([IDL.Text], [], []),
  'requestTaskRevision' : IDL.Func([IDL.Text], [], []),
  'resetAdPlacements' : IDL.Func([], [], []),
  'reviewTask' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([User], [], []),
  'setDemoDataSeeded' : IDL.Func([], [], []),
  'submitCollegeVerification' : IDL.Func(
      [IDL.Text, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'submitTaskProof' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
  'updateAdPlacement' : IDL.Func([AdType, AdPlacement], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'uploadProfilePicture' : IDL.Func([ExternalBlob], [], []),
  'verifyUser' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'proofSubmitted' : IDL.Null,
    'assigned' : IDL.Null,
    'underReview' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'pendingApproval' : IDL.Null,
    'rejected' : IDL.Null,
    'declined' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TaskProof = IDL.Record({
    'proofFiles' : IDL.Vec(ExternalBlob),
    'submittedAt' : Time,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'provider' : IDL.Principal,
    'timeRequired' : IDL.Text,
    'acceptanceDeadline' : IDL.Opt(Time),
    'revisionCount' : IDL.Nat,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'proof' : TaskProof,
    'acceptedBy' : IDL.Opt(IDL.Principal),
    'paymentAmount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const ActivityAction = IDL.Variant({
    'walletDebited' : IDL.Null,
    'walletCredited' : IDL.Null,
    'withdrawalApproved' : IDL.Null,
    'taskApproved' : IDL.Null,
    'proofUploaded' : IDL.Null,
    'taskRejected' : IDL.Null,
    'withdrawalRequested' : IDL.Null,
    'taskCreated' : IDL.Null,
    'taskAccepted' : IDL.Null,
  });
  const ActivityLogEntry = IDL.Record({
    'action' : ActivityAction,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'relatedTask' : IDL.Opt(IDL.Text),
  });
  const AdType = IDL.Variant({
    'taskBanner' : IDL.Null,
    'taskCompletionInterstitial' : IDL.Null,
    'dashboardBanner' : IDL.Null,
  });
  const AdPlacement = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'adType' : AdType,
    'frequency' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'taskPayment' : IDL.Null,
    'payout' : IDL.Null,
  });
  const TransactionRecord = IDL.Record({
    'id' : IDL.Text,
    'transactionDate' : Time,
    'transactionType' : TransactionType,
    'user' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const TransactionRecordExtended = IDL.Record({
    'id' : IDL.Text,
    'transactionDate' : Time,
    'transactionType' : TransactionType,
    'user' : IDL.Principal,
    'relatedTaskId' : IDL.Opt(IDL.Text),
    'relatedTaskTitle' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UserAppRole = IDL.Variant({
    'taskPoster' : IDL.Null,
    'business' : IDL.Null,
    'student' : IDL.Null,
  });
  const User = IDL.Record({
    'pendingVerification' : IDL.Bool,
    'verified' : IDL.Bool,
    'appRole' : UserAppRole,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'verificationDocument' : IDL.Opt(ExternalBlob),
    'phoneNumber' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'college' : IDL.Text,
  });
  const VerificationRequest = IDL.Record({
    'user' : IDL.Principal,
    'verificationDocument' : ExternalBlob,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : WithdrawalStatus,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTask' : IDL.Func([IDL.Text], [], []),
    'applyForTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'approveTask' : IDL.Func([IDL.Text], [], []),
    'approveWithdrawRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([Task], [], []),
    'createWithdrawRequest' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'depositToWallet' : IDL.Func([IDL.Nat], [], []),
    'ensureDemoDataSeeded' : IDL.Func([], [], []),
    'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLogEntry)], ['query']),
    'getAdPlacement' : IDL.Func([AdType], [AdPlacement], ['query']),
    'getAdPlacements' : IDL.Func([], [IDL.Vec(AdPlacement)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getAllTransactionHistoryExtended' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecordExtended)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepositBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getOpenTasks' : IDL.Func([], [IDL.Vec(Task)], []),
    'getPendingVerificationRequests' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequest)],
        ['query'],
      ),
    'getPendingWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getProofFiles' : IDL.Func([IDL.Text], [IDL.Vec(ExternalBlob)], ['query']),
    'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'getTasksByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getUserAppRole' : IDL.Func([], [IDL.Opt(UserAppRole)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDemoDataSeeded' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func(
        [UserRole, UserAppRole, IDL.Text, IDL.Text],
        [UserRole],
        [],
      ),
    'rejectWithdrawRequest' : IDL.Func([IDL.Text], [], []),
    'requestTaskRevision' : IDL.Func([IDL.Text], [], []),
    'resetAdPlacements' : IDL.Func([], [], []),
    'reviewTask' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([User], [], []),
    'setDemoDataSeeded' : IDL.Func([], [], []),
    'submitCollegeVerification' : IDL.Func(
        [IDL.Text, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'submitTaskProof' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
    'updateAdPlacement' : IDL.Func([AdType, AdPlacement], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'uploadProfilePicture' : IDL.Func([ExternalBlob], [], []),
    'verifyUser' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };