/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransactionRecordExtended {
    id: string;
    transactionDate: Time;
    transactionType: TransactionType;
    user: Principal;
    relatedTaskId?: string;
    relatedTaskTitle?: string;
    amount: bigint;
}
export interface AdPlacement {
    id: string;
    content: string;
    adType: AdType;
    frequency: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface User {
    pendingVerification: boolean;
    verified: boolean;
    appRole: UserAppRole;
    name: string;
    year: bigint;
    verificationDocument?: ExternalBlob;
    phoneNumber: string;
    profilePicture?: ExternalBlob;
    college: string;
}
export interface Task {
    id: string;
    status: TaskStatus;
    title: string;
    provider: Principal;
    timeRequired: string;
    acceptanceDeadline?: Time;
    revisionCount: bigint;
    description: string;
    category: string;
    proof: TaskProof;
    acceptedBy?: Principal;
    paymentAmount: bigint;
    location: string;
}
export interface TaskProof {
    proofFiles: Array<ExternalBlob>;
    submittedAt: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ActivityLogEntry {
    action: ActivityAction;
    user: Principal;
    timestamp: Time;
    relatedTask?: string;
}
export interface TransactionRecord {
    id: string;
    transactionDate: Time;
    transactionType: TransactionType;
    user: Principal;
    amount: bigint;
}
export interface WithdrawalRequest {
    id: string;
    status: WithdrawalStatus;
    createdAt: Time;
    user: Principal;
    amount: bigint;
}
export interface VerificationRequest {
    user: Principal;
    verificationDocument: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ActivityAction {
    walletDebited = "walletDebited",
    walletCredited = "walletCredited",
    withdrawalApproved = "withdrawalApproved",
    taskApproved = "taskApproved",
    proofUploaded = "proofUploaded",
    taskRejected = "taskRejected",
    withdrawalRequested = "withdrawalRequested",
    taskCreated = "taskCreated",
    taskAccepted = "taskAccepted"
}
export enum AdType {
    taskBanner = "taskBanner",
    taskCompletionInterstitial = "taskCompletionInterstitial",
    dashboardBanner = "dashboardBanner"
}
export enum TaskStatus {
    proofSubmitted = "proofSubmitted",
    assigned = "assigned",
    underReview = "underReview",
    open = "open",
    completed = "completed",
    pendingApproval = "pendingApproval",
    rejected = "rejected",
    declined = "declined",
    inProgress = "inProgress"
}
export enum TransactionType {
    deposit = "deposit",
    withdrawal = "withdrawal",
    taskPayment = "taskPayment",
    payout = "payout"
}
export enum UserAppRole {
    taskPoster = "taskPoster",
    business = "business",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptTask(taskId: string): Promise<void>;
    applyForTask(id: string, taskId: string): Promise<void>;
    approveTask(taskId: string): Promise<void>;
    approveWithdrawRequest(requestId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTask(task: Task): Promise<void>;
    createWithdrawRequest(withdrawalId: string, amount: bigint): Promise<void>;
    depositToWallet(amount: bigint): Promise<void>;
    ensureDemoDataSeeded(): Promise<void>;
    getActivityLog(): Promise<Array<ActivityLogEntry>>;
    getAdPlacement(_adType: AdType): Promise<AdPlacement>;
    getAdPlacements(): Promise<Array<AdPlacement>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllTransactionHistory(): Promise<Array<TransactionRecord>>;
    getAllTransactionHistoryExtended(): Promise<Array<TransactionRecordExtended>>;
    getCallerUserProfile(): Promise<User | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDepositBalance(): Promise<bigint>;
    getOpenTasks(): Promise<Array<Task>>;
    getPendingVerificationRequests(): Promise<Array<VerificationRequest>>;
    getPendingWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getProofFiles(taskId: string): Promise<Array<ExternalBlob>>;
    getTask(taskId: string): Promise<Task | null>;
    getTasksByUser(user: Principal): Promise<Array<Task>>;
    getTransactionHistory(): Promise<Array<TransactionRecord>>;
    getUserAppRole(): Promise<UserAppRole | null>;
    getUserProfile(userId: Principal): Promise<User | null>;
    getUserRole(): Promise<UserRole>;
    getWalletBalance(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    isDemoDataSeeded(): Promise<boolean>;
    register(userType: UserRole, appRole: UserAppRole, name: string, phoneNumber: string): Promise<UserRole>;
    rejectWithdrawRequest(requestId: string): Promise<void>;
    requestTaskRevision(taskId: string): Promise<void>;
    resetAdPlacements(): Promise<void>;
    reviewTask(taskId: string, approve: boolean): Promise<void>;
    saveCallerUserProfile(profile: User): Promise<void>;
    setDemoDataSeeded(): Promise<void>;
    submitCollegeVerification(college: string, year: bigint, verificationDocument: ExternalBlob): Promise<void>;
    submitTaskProof(taskId: string, proofFiles: Array<ExternalBlob>): Promise<void>;
    updateAdPlacement(adType: AdType, newAd: AdPlacement): Promise<void>;
    updateProfile(college: string, year: bigint): Promise<void>;
    uploadProfilePicture(profilePicture: ExternalBlob): Promise<void>;
    verifyUser(userId: Principal, approve: boolean): Promise<void>;
}
import type { ActivityAction as _ActivityAction, ActivityLogEntry as _ActivityLogEntry, AdPlacement as _AdPlacement, AdType as _AdType, ExternalBlob as _ExternalBlob, Task as _Task, TaskProof as _TaskProof, TaskStatus as _TaskStatus, Time as _Time, TransactionRecord as _TransactionRecord, TransactionRecordExtended as _TransactionRecordExtended, TransactionType as _TransactionType, User as _User, UserAppRole as _UserAppRole, UserRole as _UserRole, VerificationRequest as _VerificationRequest, WithdrawalRequest as _WithdrawalRequest, WithdrawalStatus as _WithdrawalStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTask(arg0);
            return result;
        }
    }
    async applyForTask(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForTask(arg0, arg1);
            return result;
        }
    }
    async approveTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTask(arg0);
            return result;
        }
    }
    async approveWithdrawRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(await to_candid_Task_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(await to_candid_Task_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createWithdrawRequest(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWithdrawRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWithdrawRequest(arg0, arg1);
            return result;
        }
    }
    async depositToWallet(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.depositToWallet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.depositToWallet(arg0);
            return result;
        }
    }
    async ensureDemoDataSeeded(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ensureDemoDataSeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ensureDemoDataSeeded();
            return result;
        }
    }
    async getActivityLog(): Promise<Array<ActivityLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdPlacement(arg0: AdType): Promise<AdPlacement> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdPlacement(to_candid_AdType_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdPlacement_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdPlacement(to_candid_AdType_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdPlacement_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdPlacements(): Promise<Array<AdPlacement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdPlacements();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdPlacements();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactionHistory(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactionHistory();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactionHistory();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactionHistoryExtended(): Promise<Array<TransactionRecordExtended>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactionHistoryExtended();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactionHistoryExtended();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepositBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepositBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepositBalance();
            return result;
        }
    }
    async getOpenTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenTasks();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenTasks();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingVerificationRequests(): Promise<Array<VerificationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingVerificationRequests();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingVerificationRequests();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingWithdrawalRequests();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingWithdrawalRequests();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProofFiles(arg0: string): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProofFiles(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProofFiles(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: string): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByUser(arg0: Principal): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByUser(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByUser(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAppRole(): Promise<UserAppRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAppRole();
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAppRole();
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole();
                return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole();
            return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isDemoDataSeeded(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isDemoDataSeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isDemoDataSeeded();
            return result;
        }
    }
    async register(arg0: UserRole, arg1: UserAppRole, arg2: string, arg3: string): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg0), to_candid_UserAppRole_n68(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg0), to_candid_UserAppRole_n68(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectWithdrawRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawRequest(arg0);
            return result;
        }
    }
    async requestTaskRevision(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestTaskRevision(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestTaskRevision(arg0);
            return result;
        }
    }
    async resetAdPlacements(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdPlacements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdPlacements();
            return result;
        }
    }
    async reviewTask(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewTask(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: User): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_User_n70(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_User_n70(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setDemoDataSeeded(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDemoDataSeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDemoDataSeeded();
            return result;
        }
    }
    async submitCollegeVerification(arg0: string, arg1: bigint, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCollegeVerification(arg0, arg1, await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCollegeVerification(arg0, arg1, await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async submitTaskProof(arg0: string, arg1: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTaskProof(arg0, await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTaskProof(arg0, await to_candid_vec_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateAdPlacement(arg0: AdType, arg1: AdPlacement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdPlacement(to_candid_AdType_n24(this._uploadFile, this._downloadFile, arg0), to_candid_AdPlacement_n72(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdPlacement(to_candid_AdType_n24(this._uploadFile, this._downloadFile, arg0), to_candid_AdPlacement_n72(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return result;
        }
    }
    async uploadProfilePicture(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProfilePicture(await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProfilePicture(await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyUser(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUser(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ActivityAction_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityAction): ActivityAction {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityLogEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLogEntry): ActivityLogEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_AdPlacement_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdPlacement): AdPlacement {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_AdType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdType): AdType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_TaskProof_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskProof): Promise<TaskProof> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Task_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Promise<Task> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionRecordExtended_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionRecordExtended): TransactionRecordExtended {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionRecord_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionRecord): TransactionRecord {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserAppRole_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAppRole): UserAppRole {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
async function from_candid_User_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): Promise<User> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
async function from_candid_VerificationRequest_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationRequest): Promise<VerificationRequest> {
    return await from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): Promise<User | null> {
    return value.length === 0 ? null : await from_candid_User_n51(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Promise<Task | null> {
    return value.length === 0 ? null : await from_candid_Task_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserAppRole]): UserAppRole | null {
    return value.length === 0 ? null : from_candid_UserAppRole_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: _ActivityAction;
    user: Principal;
    timestamp: _Time;
    relatedTask: [] | [string];
}): {
    action: ActivityAction;
    user: Principal;
    timestamp: Time;
    relatedTask?: string;
} {
    return {
        action: from_candid_ActivityAction_n21(_uploadFile, _downloadFile, value.action),
        user: value.user,
        timestamp: value.timestamp,
        relatedTask: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.relatedTask))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    adType: _AdType;
    frequency: bigint;
}): {
    id: string;
    content: string;
    adType: AdType;
    frequency: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        adType: from_candid_AdType_n28(_uploadFile, _downloadFile, value.adType),
        frequency: value.frequency
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TaskStatus;
    title: string;
    provider: Principal;
    timeRequired: string;
    acceptanceDeadline: [] | [_Time];
    revisionCount: bigint;
    description: string;
    category: string;
    proof: _TaskProof;
    acceptedBy: [] | [Principal];
    paymentAmount: bigint;
    location: string;
}): Promise<{
    id: string;
    status: TaskStatus;
    title: string;
    provider: Principal;
    timeRequired: string;
    acceptanceDeadline?: Time;
    revisionCount: bigint;
    description: string;
    category: string;
    proof: TaskProof;
    acceptedBy?: Principal;
    paymentAmount: bigint;
    location: string;
}> {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        provider: value.provider,
        timeRequired: value.timeRequired,
        acceptanceDeadline: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.acceptanceDeadline)),
        revisionCount: value.revisionCount,
        description: value.description,
        category: value.category,
        proof: await from_candid_TaskProof_n37(_uploadFile, _downloadFile, value.proof),
        acceptedBy: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.acceptedBy)),
        paymentAmount: value.paymentAmount,
        location: value.location
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proofFiles: Array<_ExternalBlob>;
    submittedAt: _Time;
}): Promise<{
    proofFiles: Array<ExternalBlob>;
    submittedAt: Time;
}> {
    return {
        proofFiles: await from_candid_vec_n39(_uploadFile, _downloadFile, value.proofFiles),
        submittedAt: value.submittedAt
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionDate: _Time;
    transactionType: _TransactionType;
    user: Principal;
    amount: bigint;
}): {
    id: string;
    transactionDate: Time;
    transactionType: TransactionType;
    user: Principal;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionDate: value.transactionDate,
        transactionType: from_candid_TransactionType_n45(_uploadFile, _downloadFile, value.transactionType),
        user: value.user,
        amount: value.amount
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionDate: _Time;
    transactionType: _TransactionType;
    user: Principal;
    relatedTaskId: [] | [string];
    relatedTaskTitle: [] | [string];
    amount: bigint;
}): {
    id: string;
    transactionDate: Time;
    transactionType: TransactionType;
    user: Principal;
    relatedTaskId?: string;
    relatedTaskTitle?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionDate: value.transactionDate,
        transactionType: from_candid_TransactionType_n45(_uploadFile, _downloadFile, value.transactionType),
        user: value.user,
        relatedTaskId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.relatedTaskId)),
        relatedTaskTitle: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.relatedTaskTitle)),
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingVerification: boolean;
    verified: boolean;
    appRole: _UserAppRole;
    name: string;
    year: bigint;
    verificationDocument: [] | [_ExternalBlob];
    phoneNumber: string;
    profilePicture: [] | [_ExternalBlob];
    college: string;
}): Promise<{
    pendingVerification: boolean;
    verified: boolean;
    appRole: UserAppRole;
    name: string;
    year: bigint;
    verificationDocument?: ExternalBlob;
    phoneNumber: string;
    profilePicture?: ExternalBlob;
    college: string;
}> {
    return {
        pendingVerification: value.pendingVerification,
        verified: value.verified,
        appRole: from_candid_UserAppRole_n53(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        year: value.year,
        verificationDocument: record_opt_to_undefined(await from_candid_opt_n55(_uploadFile, _downloadFile, value.verificationDocument)),
        phoneNumber: value.phoneNumber,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n55(_uploadFile, _downloadFile, value.profilePicture)),
        college: value.college
    };
}
async function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    verificationDocument: _ExternalBlob;
}): Promise<{
    user: Principal;
    verificationDocument: ExternalBlob;
}> {
    return {
        user: value.user,
        verificationDocument: await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value.verificationDocument)
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _WithdrawalStatus;
    createdAt: _Time;
    user: Principal;
    amount: bigint;
}): {
    id: string;
    status: WithdrawalStatus;
    createdAt: Time;
    user: Principal;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n64(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        user: value.user,
        amount: value.amount
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    walletDebited: null;
} | {
    walletCredited: null;
} | {
    withdrawalApproved: null;
} | {
    taskApproved: null;
} | {
    proofUploaded: null;
} | {
    taskRejected: null;
} | {
    withdrawalRequested: null;
} | {
    taskCreated: null;
} | {
    taskAccepted: null;
}): ActivityAction {
    return "walletDebited" in value ? ActivityAction.walletDebited : "walletCredited" in value ? ActivityAction.walletCredited : "withdrawalApproved" in value ? ActivityAction.withdrawalApproved : "taskApproved" in value ? ActivityAction.taskApproved : "proofUploaded" in value ? ActivityAction.proofUploaded : "taskRejected" in value ? ActivityAction.taskRejected : "withdrawalRequested" in value ? ActivityAction.withdrawalRequested : "taskCreated" in value ? ActivityAction.taskCreated : "taskAccepted" in value ? ActivityAction.taskAccepted : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskBanner: null;
} | {
    taskCompletionInterstitial: null;
} | {
    dashboardBanner: null;
}): AdType {
    return "taskBanner" in value ? AdType.taskBanner : "taskCompletionInterstitial" in value ? AdType.taskCompletionInterstitial : "dashboardBanner" in value ? AdType.dashboardBanner : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proofSubmitted: null;
} | {
    assigned: null;
} | {
    underReview: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    pendingApproval: null;
} | {
    rejected: null;
} | {
    declined: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "proofSubmitted" in value ? TaskStatus.proofSubmitted : "assigned" in value ? TaskStatus.assigned : "underReview" in value ? TaskStatus.underReview : "open" in value ? TaskStatus.open : "completed" in value ? TaskStatus.completed : "pendingApproval" in value ? TaskStatus.pendingApproval : "rejected" in value ? TaskStatus.rejected : "declined" in value ? TaskStatus.declined : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit: null;
} | {
    withdrawal: null;
} | {
    taskPayment: null;
} | {
    payout: null;
}): TransactionType {
    return "deposit" in value ? TransactionType.deposit : "withdrawal" in value ? TransactionType.withdrawal : "taskPayment" in value ? TransactionType.taskPayment : "payout" in value ? TransactionType.payout : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskPoster: null;
} | {
    business: null;
} | {
    student: null;
}): UserAppRole {
    return "taskPoster" in value ? UserAppRole.taskPoster : "business" in value ? UserAppRole.business : "student" in value ? UserAppRole.student : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLogEntry>): Array<ActivityLogEntry> {
    return value.map((x)=>from_candid_ActivityLogEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdPlacement>): Array<AdPlacement> {
    return value.map((x)=>from_candid_AdPlacement_n26(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Promise<Array<Task>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Task_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionRecord>): Array<TransactionRecord> {
    return value.map((x)=>from_candid_TransactionRecord_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionRecordExtended>): Array<TransactionRecordExtended> {
    return value.map((x)=>from_candid_TransactionRecordExtended_n48(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VerificationRequest>): Promise<Array<VerificationRequest>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VerificationRequest_n59(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n62(_uploadFile, _downloadFile, x));
}
function to_candid_AdPlacement_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdPlacement): _AdPlacement {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_AdType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdType): _AdType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_TaskProof_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskProof): Promise<_TaskProof> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Task_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): Promise<_Task> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserAppRole_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserAppRole): _UserAppRole {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_User_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: User): Promise<_User> {
    return await to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TaskStatus;
    title: string;
    provider: Principal;
    timeRequired: string;
    acceptanceDeadline?: Time;
    revisionCount: bigint;
    description: string;
    category: string;
    proof: TaskProof;
    acceptedBy?: Principal;
    paymentAmount: bigint;
    location: string;
}): Promise<{
    id: string;
    status: _TaskStatus;
    title: string;
    provider: Principal;
    timeRequired: string;
    acceptanceDeadline: [] | [_Time];
    revisionCount: bigint;
    description: string;
    category: string;
    proof: _TaskProof;
    acceptedBy: [] | [Principal];
    paymentAmount: bigint;
    location: string;
}> {
    return {
        id: value.id,
        status: to_candid_TaskStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        provider: value.provider,
        timeRequired: value.timeRequired,
        acceptanceDeadline: value.acceptanceDeadline ? candid_some(value.acceptanceDeadline) : candid_none(),
        revisionCount: value.revisionCount,
        description: value.description,
        category: value.category,
        proof: await to_candid_TaskProof_n14(_uploadFile, _downloadFile, value.proof),
        acceptedBy: value.acceptedBy ? candid_some(value.acceptedBy) : candid_none(),
        paymentAmount: value.paymentAmount,
        location: value.location
    };
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proofFiles: Array<ExternalBlob>;
    submittedAt: Time;
}): Promise<{
    proofFiles: Array<_ExternalBlob>;
    submittedAt: _Time;
}> {
    return {
        proofFiles: await to_candid_vec_n16(_uploadFile, _downloadFile, value.proofFiles),
        submittedAt: value.submittedAt
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingVerification: boolean;
    verified: boolean;
    appRole: UserAppRole;
    name: string;
    year: bigint;
    verificationDocument?: ExternalBlob;
    phoneNumber: string;
    profilePicture?: ExternalBlob;
    college: string;
}): Promise<{
    pendingVerification: boolean;
    verified: boolean;
    appRole: _UserAppRole;
    name: string;
    year: bigint;
    verificationDocument: [] | [_ExternalBlob];
    phoneNumber: string;
    profilePicture: [] | [_ExternalBlob];
    college: string;
}> {
    return {
        pendingVerification: value.pendingVerification,
        verified: value.verified,
        appRole: to_candid_UserAppRole_n68(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        year: value.year,
        verificationDocument: value.verificationDocument ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.verificationDocument)) : candid_none(),
        phoneNumber: value.phoneNumber,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        college: value.college
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    adType: AdType;
    frequency: bigint;
}): {
    id: string;
    content: string;
    adType: _AdType;
    frequency: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        adType: to_candid_AdType_n24(_uploadFile, _downloadFile, value.adType),
        frequency: value.frequency
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    proofSubmitted: null;
} | {
    assigned: null;
} | {
    underReview: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    pendingApproval: null;
} | {
    rejected: null;
} | {
    declined: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.proofSubmitted ? {
        proofSubmitted: null
    } : value == TaskStatus.assigned ? {
        assigned: null
    } : value == TaskStatus.underReview ? {
        underReview: null
    } : value == TaskStatus.open ? {
        open: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.pendingApproval ? {
        pendingApproval: null
    } : value == TaskStatus.rejected ? {
        rejected: null
    } : value == TaskStatus.declined ? {
        declined: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdType): {
    taskBanner: null;
} | {
    taskCompletionInterstitial: null;
} | {
    dashboardBanner: null;
} {
    return value == AdType.taskBanner ? {
        taskBanner: null
    } : value == AdType.taskCompletionInterstitial ? {
        taskCompletionInterstitial: null
    } : value == AdType.dashboardBanner ? {
        dashboardBanner: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserAppRole): {
    taskPoster: null;
} | {
    business: null;
} | {
    student: null;
} {
    return value == UserAppRole.taskPoster ? {
        taskPoster: null
    } : value == UserAppRole.business ? {
        business: null
    } : value == UserAppRole.student ? {
        student: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
